(() => {
  const LANGS = [
    ['de', '🇩🇪', 'Deutsch'], ['en', '🇬🇧', 'English'], ['es', '🇪🇸', 'Español'],
    ['fr', '🇫🇷', 'Français'], ['it', '🇮🇹', 'Italiano'], ['pt', '🇵🇹', 'Português'],
    ['nl', '🇳🇱', 'Nederlands'], ['tr', '🇹🇷', 'Türkçe'], ['zh', '🇨🇳', '简体中文'], ['ja', '🇯🇵', '日本語']
  ];

  const T = {
    de: { overview:'Übersicht', portfolio:'Portfolio', watchlist:'Watchlist', signals:'Signale', intelligence:'INVESTMENT INTELLIGENCE', total:'GESAMTER PORTFOLIOWERT', invested:'INVESTIERT', cash:'VERFÜGBARES GUTHABEN', pnl:'NICHT REALISIERTER G/V', risk:'RISIKO-SCORE', live:'LIVE', performance:'PERFORMANCE', history:'Portfolio-Verlauf', allocation:'ALLOKATION', holdings:'Bestände', sentinel:'SENTINEL', marketSignals:'Marktsignale', viewAll:'Alle anzeigen →', livePositions:'LIVE-POSITIONEN', yourPortfolio:'Dein Portfolio', asset:'Asset', value:'Wert', weight:'Gewichtung', tracked:'VERFOLGTE ASSETS', trackedAssets:'Verfolgte Assets', nextStep:'NÄCHSTER SCHRITT', engine:'SENTINEL ENGINE', settings:'Einstellungen', general:'Allgemein', language:'Sprache', appearance:'Darstellung', account:'Konto', customLogo:'Eigenes Logo', uploadLogo:'Logo auswählen', removeLogo:'Logo entfernen', logoHint:'PNG, JPG, SVG oder WebP. Das Logo wird nur auf diesem Gerät gespeichert.', connected:'Trading 212 verbunden', notConnected:'Nicht verbunden', save:'Speichern', close:'Schließen', about:'Über Lumeceta Sentinel', version:'Version', refresh:'Aktualisieren', darkMode:'Dark Mode', accent:'Akzentfarbe', accentHint:'Für Lumeceta wird die violette Akzentfarbe empfohlen.', saved:'Einstellungen gespeichert ✓', logoSaved:'Eigenes Logo übernommen ✓' },
    en: { overview:'Overview', portfolio:'Portfolio', watchlist:'Watchlist', signals:'Signals', intelligence:'INVESTMENT INTELLIGENCE', total:'TOTAL PORTFOLIO VALUE', invested:'INVESTED', cash:'AVAILABLE CASH', pnl:'UNREALIZED P/L', risk:'RISK SCORE', live:'LIVE', performance:'PERFORMANCE', history:'Portfolio history', allocation:'ALLOCATION', holdings:'Holdings', sentinel:'SENTINEL', marketSignals:'Market signals', viewAll:'View all →', livePositions:'LIVE POSITIONS', yourPortfolio:'Your portfolio', asset:'Asset', value:'Value', weight:'Weight', tracked:'WATCHLIST', trackedAssets:'Tracked assets', nextStep:'NEXT STEP', engine:'SENTINEL ENGINE', settings:'Settings', general:'General', language:'Language', appearance:'Appearance', account:'Account', customLogo:'Custom logo', uploadLogo:'Choose logo', removeLogo:'Remove logo', logoHint:'PNG, JPG, SVG or WebP. The logo is stored only on this device.', connected:'Trading 212 connected', notConnected:'Not connected', save:'Save', close:'Close', about:'About Lumeceta Sentinel', version:'Version', refresh:'Refresh', darkMode:'Dark Mode', accent:'Accent color', accentHint:'Purple accent is recommended for Lumeceta.', saved:'Settings saved ✓', logoSaved:'Custom logo applied ✓' },
    es: { overview:'Resumen', portfolio:'Cartera', watchlist:'Lista de seguimiento', signals:'Señales', intelligence:'INTELIGENCIA DE INVERSIÓN', total:'VALOR TOTAL DE LA CARTERA', invested:'INVERTIDO', cash:'EFECTIVO DISPONIBLE', pnl:'G/P NO REALIZADO', risk:'RIESGO', live:'EN VIVO', performance:'RENDIMIENTO', history:'Historial de cartera', allocation:'ASIGNACIÓN', holdings:'Posiciones', sentinel:'SENTINEL', marketSignals:'Señales del mercado', viewAll:'Ver todo →', livePositions:'POSICIONES EN VIVO', yourPortfolio:'Tu cartera', asset:'Activo', value:'Valor', weight:'Peso', tracked:'LISTA DE SEGUIMIENTO', trackedAssets:'Activos seguidos', nextStep:'SIGUIENTE PASO', engine:'MOTOR SENTINEL', settings:'Ajustes', general:'General', language:'Idioma', appearance:'Apariencia', account:'Cuenta', customLogo:'Logotipo propio', uploadLogo:'Elegir logotipo', removeLogo:'Eliminar logotipo', logoHint:'PNG, JPG, SVG o WebP. Se guarda solo en este dispositivo.', connected:'Trading 212 conectado', notConnected:'No conectado', save:'Guardar', close:'Cerrar', about:'Acerca de Lumeceta Sentinel', version:'Versión', refresh:'Actualizar', darkMode:'Modo oscuro', accent:'Color de acento', accentHint:'Se recomienda el violeta para Lumeceta.', saved:'Ajustes guardados ✓', logoSaved:'Logotipo propio aplicado ✓' },
    fr: { overview:'Vue d’ensemble', portfolio:'Portefeuille', watchlist:'Liste de suivi', signals:'Signaux', intelligence:'INTELLIGENCE D’INVESTISSEMENT', total:'VALEUR TOTALE DU PORTEFEUILLE', invested:'INVESTI', cash:'LIQUIDITÉS DISPONIBLES', pnl:'P/L NON RÉALISÉ', risk:'SCORE DE RISQUE', live:'EN DIRECT', performance:'PERFORMANCE', history:'Historique du portefeuille', allocation:'RÉPARTITION', holdings:'Positions', sentinel:'SENTINEL', marketSignals:'Signaux du marché', viewAll:'Tout voir →', livePositions:'POSITIONS EN DIRECT', yourPortfolio:'Votre portefeuille', asset:'Actif', value:'Valeur', weight:'Poids', tracked:'LISTE DE SUIVI', trackedAssets:'Actifs suivis', nextStep:'ÉTAPE SUIVANTE', engine:'MOTEUR SENTINEL', settings:'Paramètres', general:'Général', language:'Langue', appearance:'Apparence', account:'Compte', customLogo:'Logo personnalisé', uploadLogo:'Choisir un logo', removeLogo:'Supprimer le logo', logoHint:'PNG, JPG, SVG ou WebP. Le logo est stocké uniquement sur cet appareil.', connected:'Trading 212 connecté', notConnected:'Non connecté', save:'Enregistrer', close:'Fermer', about:'À propos de Lumeceta Sentinel', version:'Version', refresh:'Actualiser', darkMode:'Mode sombre', accent:'Couleur d’accent', accentHint:'Le violet est recommandé pour Lumeceta.', saved:'Paramètres enregistrés ✓', logoSaved:'Logo personnalisé appliqué ✓' },
    it: { overview:'Panoramica', portfolio:'Portafoglio', watchlist:'Lista osservati', signals:'Segnali', intelligence:'INTELLIGENZA DEGLI INVESTIMENTI', total:'VALORE TOTALE DEL PORTAFOGLIO', invested:'INVESTITO', cash:'LIQUIDITÀ DISPONIBILE', pnl:'P/L NON REALIZZATO', risk:'PUNTEGGIO RISCHIO', live:'LIVE', performance:'PERFORMANCE', history:'Storico portafoglio', allocation:'ALLOCAZIONE', holdings:'Posizioni', sentinel:'SENTINEL', marketSignals:'Segnali di mercato', viewAll:'Vedi tutto →', livePositions:'POSIZIONI LIVE', yourPortfolio:'Il tuo portafoglio', asset:'Asset', value:'Valore', weight:'Peso', tracked:'WATCHLIST', trackedAssets:'Asset monitorati', nextStep:'PROSSIMO PASSO', engine:'MOTORE SENTINEL', settings:'Impostazioni', general:'Generale', language:'Lingua', appearance:'Aspetto', account:'Account', customLogo:'Logo personalizzato', uploadLogo:'Scegli logo', removeLogo:'Rimuovi logo', logoHint:'PNG, JPG, SVG o WebP. Il logo viene salvato solo su questo dispositivo.', connected:'Trading 212 connesso', notConnected:'Non connesso', save:'Salva', close:'Chiudi', about:'Informazioni su Lumeceta Sentinel', version:'Versione', refresh:'Aggiorna', darkMode:'Modalità scura', accent:'Colore accento', accentHint:'Per Lumeceta si consiglia il viola.', saved:'Impostazioni salvate ✓', logoSaved:'Logo personalizzato applicato ✓' },
    pt: { overview:'Visão geral', portfolio:'Portfólio', watchlist:'Lista de observação', signals:'Sinais', intelligence:'INTELIGÊNCIA DE INVESTIMENTO', total:'VALOR TOTAL DO PORTFÓLIO', invested:'INVESTIDO', cash:'CAIXA DISPONÍVEL', pnl:'L/P NÃO REALIZADO', risk:'PONTUAÇÃO DE RISCO', live:'AO VIVO', performance:'DESEMPENHO', history:'Histórico do portfólio', allocation:'ALOCAÇÃO', holdings:'Posições', sentinel:'SENTINEL', marketSignals:'Sinais de mercado', viewAll:'Ver tudo →', livePositions:'POSIÇÕES AO VIVO', yourPortfolio:'Seu portfólio', asset:'Ativo', value:'Valor', weight:'Peso', tracked:'LISTA DE OBSERVAÇÃO', trackedAssets:'Ativos monitorados', nextStep:'PRÓXIMO PASSO', engine:'MOTOR SENTINEL', settings:'Definições', general:'Geral', language:'Idioma', appearance:'Aparência', account:'Conta', customLogo:'Logótipo personalizado', uploadLogo:'Escolher logótipo', removeLogo:'Remover logótipo', logoHint:'PNG, JPG, SVG ou WebP. Guardado apenas neste dispositivo.', connected:'Trading 212 ligado', notConnected:'Não ligado', save:'Guardar', close:'Fechar', about:'Sobre o Lumeceta Sentinel', version:'Versão', refresh:'Atualizar', darkMode:'Modo escuro', accent:'Cor de destaque', accentHint:'O violeta é recomendado para o Lumeceta.', saved:'Definições guardadas ✓', logoSaved:'Logótipo personalizado aplicado ✓' },
    nl: { overview:'Overzicht', portfolio:'Portfolio', watchlist:'Volglijst', signals:'Signalen', intelligence:'BELEGGINGSINTELLIGENTIE', total:'TOTALE PORTEFEUILLEWAARDE', invested:'GEÏNVESTEERD', cash:'BESCHIKBAAR GELD', pnl:'ONGEREALISEERDE W/V', risk:'RISICOSCORE', live:'LIVE', performance:'PRESTATIES', history:'Portefeuillehistorie', allocation:'ALLOCATIE', holdings:'Posities', sentinel:'SENTINEL', marketSignals:'Marktsignalen', viewAll:'Alles bekijken →', livePositions:'LIVE POSITIES', yourPortfolio:'Jouw portfolio', asset:'Asset', value:'Waarde', weight:'Gewicht', tracked:'VOLGLIJST', trackedAssets:'Gevolgde assets', nextStep:'VOLGENDE STAP', engine:'SENTINEL ENGINE', settings:'Instellingen', general:'Algemeen', language:'Taal', appearance:'Weergave', account:'Account', customLogo:'Eigen logo', uploadLogo:'Logo kiezen', removeLogo:'Logo verwijderen', logoHint:'PNG, JPG, SVG of WebP. Alleen op dit apparaat opgeslagen.', connected:'Trading 212 verbonden', notConnected:'Niet verbonden', save:'Opslaan', close:'Sluiten', about:'Over Lumeceta Sentinel', version:'Versie', refresh:'Vernieuwen', darkMode:'Donkere modus', accent:'Accentkleur', accentHint:'Paars wordt aanbevolen voor Lumeceta.', saved:'Instellingen opgeslagen ✓', logoSaved:'Eigen logo toegepast ✓' },
    tr: { overview:'Genel Bakış', portfolio:'Portföy', watchlist:'İzleme Listesi', signals:'Sinyaller', intelligence:'YATIRIM ZEKA SİSTEMİ', total:'TOPLAM PORTFÖY DEĞERİ', invested:'YATIRILAN', cash:'KULLANILABİLİR NAKİT', pnl:'GERÇEKLEŞMEMİŞ K/Z', risk:'RİSK SKORU', live:'CANLI', performance:'PERFORMANS', history:'Portföy geçmişi', allocation:'DAĞILIM', holdings:'Varlıklar', sentinel:'SENTINEL', marketSignals:'Piyasa sinyalleri', viewAll:'Tümünü gör →', livePositions:'CANLI POZİSYONLAR', yourPortfolio:'Portföyün', asset:'Varlık', value:'Değer', weight:'Ağırlık', tracked:'İZLEME LİSTESİ', trackedAssets:'İzlenen varlıklar', nextStep:'SONRAKİ ADIM', engine:'SENTINEL MOTORU', settings:'Ayarlar', general:'Genel', language:'Dil', appearance:'Görünüm', account:'Hesap', customLogo:'Özel logo', uploadLogo:'Logo seç', removeLogo:'Logoyu kaldır', logoHint:'PNG, JPG, SVG veya WebP. Yalnızca bu cihazda saklanır.', connected:'Trading 212 bağlı', notConnected:'Bağlı değil', save:'Kaydet', close:'Kapat', about:'Lumeceta Sentinel hakkında', version:'Sürüm', refresh:'Yenile', darkMode:'Karanlık mod', accent:'Vurgu rengi', accentHint:'Lumeceta için mor önerilir.', saved:'Ayarlar kaydedildi ✓', logoSaved:'Özel logo uygulandı ✓' },
    zh: { overview:'总览', portfolio:'投资组合', watchlist:'关注列表', signals:'信号', intelligence:'投资智能', total:'投资组合总价值', invested:'已投资', cash:'可用现金', pnl:'未实现盈亏', risk:'风险评分', live:'实时', performance:'表现', history:'投资组合历史', allocation:'资产配置', holdings:'持仓', sentinel:'SENTINEL', marketSignals:'市场信号', viewAll:'查看全部 →', livePositions:'实时持仓', yourPortfolio:'你的投资组合', asset:'资产', value:'价值', weight:'权重', tracked:'关注列表', trackedAssets:'关注资产', nextStep:'下一步', engine:'SENTINEL 引擎', settings:'设置', general:'常规', language:'语言', appearance:'外观', account:'账户', customLogo:'自定义 Logo', uploadLogo:'选择 Logo', removeLogo:'移除 Logo', logoHint:'PNG、JPG、SVG 或 WebP，仅保存在此设备。', connected:'Trading 212 已连接', notConnected:'未连接', save:'保存', close:'关闭', about:'关于 Lumeceta Sentinel', version:'版本', refresh:'刷新', darkMode:'深色模式', accent:'强调色', accentHint:'建议使用 Lumeceta 紫色。', saved:'设置已保存 ✓', logoSaved:'自定义 Logo 已应用 ✓' },
    ja: { overview:'概要', portfolio:'ポートフォリオ', watchlist:'ウォッチリスト', signals:'シグナル', intelligence:'投資インテリジェンス', total:'ポートフォリオ総額', invested:'投資額', cash:'利用可能な現金', pnl:'未実現損益', risk:'リスクスコア', live:'ライブ', performance:'パフォーマンス', history:'ポートフォリオ履歴', allocation:'配分', holdings:'保有資産', sentinel:'SENTINEL', marketSignals:'市場シグナル', viewAll:'すべて表示 →', livePositions:'ライブポジション', yourPortfolio:'あなたのポートフォリオ', asset:'資産', value:'価値', weight:'比率', tracked:'ウォッチリスト', trackedAssets:'追跡中の資産', nextStep:'次のステップ', engine:'SENTINEL エンジン', settings:'設定', general:'一般', language:'言語', appearance:'外観', account:'アカウント', customLogo:'カスタムロゴ', uploadLogo:'ロゴを選択', removeLogo:'ロゴを削除', logoHint:'PNG、JPG、SVG、WebP。端末内にのみ保存されます。', connected:'Trading 212 接続済み', notConnected:'未接続', save:'保存', close:'閉じる', about:'Lumeceta Sentinel について', version:'バージョン', refresh:'更新', darkMode:'ダークモード', accent:'アクセントカラー', accentHint:'Lumeceta には紫がおすすめです。', saved:'設定を保存しました ✓', logoSaved:'カスタムロゴを適用しました ✓' }
  };

  let lang = localStorage.getItem('lumeceta.language') || 'de';

  const t = key => (T[lang] && T[lang][key]) || T.en[key] || key;

  function replaceText(selector, key) {
    const el = document.querySelector(selector);
    if (el) el.textContent = t(key);
  }

  function applyLanguage() {
    document.documentElement.lang = lang;
    replaceText('.nav-item[data-view="overview"] span', 'overview');
    replaceText('.nav-item[data-view="portfolio"] span', 'portfolio');
    replaceText('.nav-item[data-view="watchlist"] span', 'watchlist');
    replaceText('.nav-item[data-view="signals"] span', 'signals');
    replaceText('.hero-card .muted', 'total');
    const metrics = document.querySelectorAll('#view-overview .metric .muted:first-child');
    ['invested','cash','pnl','risk'].forEach((key,i)=>{ if(metrics[i]) metrics[i].textContent=t(key); });
    const heads = document.querySelectorAll('#view-overview .two-col .section-head .muted');
    if(heads[0]) heads[0].textContent=t('performance');
    if(heads[1]) heads[1].textContent=t('allocation');
    const h2 = document.querySelectorAll('#view-overview .two-col h2');
    if(h2[0]) h2[0].textContent=t('history');
    if(h2[1]) h2[1].textContent=t('holdings');
    const sentinel = document.querySelector('#view-overview > section.card:last-of-type');
    if(sentinel){ const m=sentinel.querySelector('.muted'); const h=sentinel.querySelector('h2'); const b=sentinel.querySelector('.text-btn'); if(m)m.textContent=t('sentinel'); if(h)h.textContent=t('marketSignals'); if(b)b.textContent=t('viewAll'); }
    const portHead=document.querySelector('#view-portfolio .section-head'); if(portHead){ const m=portHead.querySelector('.muted'),h=portHead.querySelector('h2'); if(m)m.textContent=t('livePositions'); if(h)h.textContent=t('yourPortfolio'); }
    const ph=document.querySelectorAll('#view-portfolio .table-head span'); ['asset','value','pnl','weight'].forEach((key,i)=>{if(ph[i])ph[i].textContent=t(key);});
    const watch=document.querySelector('#view-watchlist .section-head'); if(watch){const m=watch.querySelector('.muted'),h=watch.querySelector('h2'),p=watch.querySelector('.pill');if(m)m.textContent=t('tracked');if(h)h.textContent=t('trackedAssets');if(p)p.textContent=t('nextStep');}
    const sig=document.querySelector('#view-signals .section-head'); if(sig){const m=sig.querySelector('.muted'),h=sig.querySelector('h2');if(m)m.textContent=t('engine');if(h)h.textContent=t('signals');}
    const connect=document.getElementById('connect-btn'); if(connect && !connect.textContent.includes('✓')) connect.textContent=t('connected');
    const status=document.getElementById('connection-label'); if(status) status.textContent=status.textContent.includes('connected')||status.textContent.includes('verbunden')?t('connected'):t('notConnected');
    replaceText('#refresh','refresh');
    replaceText('#page-title', ({overview:'overview',portfolio:'portfolio',watchlist:'watchlist',signals:'signals'})[location.hash.slice(1)] || 'overview');
    const settingsBtn=document.getElementById('settings-btn'); if(settingsBtn) settingsBtn.title=t('settings');
    renderSettings();
  }

  function applyLogo(dataUrl) {
    let img=document.getElementById('brand-logo');
    if(!img){
      const brand=document.querySelector('.brand');
      if(!brand)return;
      brand.innerHTML='<img id="brand-logo" class="brand-logo" alt="Lumeceta logo"><span>LUMECETA</span>';
      img=document.getElementById('brand-logo');
    }
    if(dataUrl){ img.src=dataUrl; img.classList.add('has-logo'); document.querySelector('.brand-mark')?.classList.add('logo-hidden'); }
    else { img.removeAttribute('src'); img.classList.remove('has-logo'); }
  }

  function setupBrand(){
    const brand=document.querySelector('.brand');
    if(brand && !document.getElementById('brand-logo')) brand.innerHTML='<img id="brand-logo" class="brand-logo" alt="Lumeceta logo"><span>LUMECETA</span>';
    applyLogo(localStorage.getItem('lumeceta.logo') || '');
  }

  function injectSettings(){
    const top=document.querySelector('.top-actions');
    if(!top || document.getElementById('settings-btn')) return;
    const btn=document.createElement('button'); btn.id='settings-btn'; btn.className='icon-btn settings-btn'; btn.textContent='⚙'; btn.title=t('settings'); top.insertBefore(btn, top.querySelector('.avatar'));
    const drawer=document.createElement('div'); drawer.id='settings-drawer'; drawer.className='settings-backdrop';
    drawer.innerHTML='<aside class="settings-panel"><div class="settings-header"><div><div class="muted">LUMECETA</div><h2 id="settings-title"></h2></div><button id="settings-close" class="modal-close">×</button></div><div class="settings-tabs"><button class="settings-tab active" data-tab="general"></button><button class="settings-tab" data-tab="account"></button><button class="settings-tab" data-tab="appearance"></button></div><section class="settings-section active" data-section="general"><label class="settings-label" id="language-label"></label><select id="language-select"></select><div class="setting-card"><div><strong id="custom-logo-label"></strong><p id="logo-hint"></p></div><input id="logo-input" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"><label for="logo-input" class="primary-btn logo-upload" id="upload-logo-label"></label><button id="remove-logo" class="secondary-btn"></button></div></section><section class="settings-section" data-section="account"><div class="setting-card"><div><strong>Trading 212</strong><p id="account-status-text"></p></div><span class="settings-live-dot">●</span></div></section><section class="settings-section" data-section="appearance"><div class="setting-card"><div><strong id="dark-mode-label"></strong><p>Dark-Tech UI</p></div><label class="switch"><input id="dark-mode" type="checkbox" checked><span></span></label></div><div class="setting-card"><div><strong id="accent-label"></strong><p id="accent-hint"></p></div><span class="accent-preview"></span></div></section><div class="settings-footer"><span id="about-label"></span><span>v0.3.0</span></div></aside>';
    document.body.appendChild(drawer);
    btn.addEventListener('click',()=>{drawer.classList.add('open');renderSettings();});
    drawer.querySelector('#settings-close').addEventListener('click',()=>drawer.classList.remove('open'));
    drawer.addEventListener('click',e=>{if(e.target===drawer)drawer.classList.remove('open');});
    drawer.querySelectorAll('.settings-tab').forEach(tab=>tab.addEventListener('click',()=>{drawer.querySelectorAll('.settings-tab').forEach(x=>x.classList.toggle('active',x===tab));drawer.querySelectorAll('.settings-section').forEach(x=>x.classList.toggle('active',x.dataset.section===tab.dataset.tab));}));
    drawer.querySelector('#language-select').addEventListener('change',e=>{lang=e.target.value;localStorage.setItem('lumeceta.language',lang);applyLanguage();});
    drawer.querySelector('#logo-input').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{localStorage.setItem('lumeceta.logo',reader.result);applyLogo(reader.result);showToastSafe(t('logoSaved'));};reader.readAsDataURL(file);});
    drawer.querySelector('#remove-logo').addEventListener('click',()=>{localStorage.removeItem('lumeceta.logo');applyLogo('');showToastSafe(t('saved'));});
    drawer.querySelector('#dark-mode').addEventListener('change',e=>{document.documentElement.dataset.theme=e.target.checked?'dark':'light';localStorage.setItem('lumeceta.darkMode',e.target.checked?'dark':'light');});
  }

  function showToastSafe(message){ if(typeof window.showToast==='function') window.showToast(message); else { const toast=document.getElementById('toast');if(toast){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);} } }

  function renderSettings(){
    const set=(id,key)=>{const e=document.getElementById(id);if(e)e.textContent=t(key);};
    set('settings-title','settings');set('language-label','language');set('custom-logo-label','customLogo');set('logo-hint','logoHint');set('upload-logo-label','uploadLogo');set('remove-logo','removeLogo');set('account-status-text','connected');set('dark-mode-label','darkMode');set('accent-label','accent');set('accent-hint','accentHint');set('about-label','about');
    document.querySelectorAll('.settings-tab').forEach(tab=>tab.textContent=t(tab.dataset.tab));
    const select=document.getElementById('language-select');if(select){select.innerHTML=LANGS.map(([code,flag,name])=>`<option value="${code}">${flag} ${name}</option>`).join('');select.value=lang;}
  }

  setupBrand(); injectSettings(); applyLanguage();
  const mode=localStorage.getItem('lumeceta.darkMode')||'dark';document.documentElement.dataset.theme=mode;
  window.LumecetaSettings={getLanguage:()=>lang,setLanguage:(value)=>{if(T[value]){lang=value;localStorage.setItem('lumeceta.language',value);applyLanguage();}}};
})();
